#FROM node:20.1.0
#WORKDIR /client
## Copy package.json and package-lock.json to the /app directory
#COPY package.json package-lock.json ./
#
#RUN npm install
#COPY . .
#
##RUN npm run build
#
## Expose application port
#EXPOSE 5173
#
#CMD [ "npm", "run", "dev", "--", "--host"]
